flows: 
  - id: FEATURE_DISCOVERY
    devPortal: true
    lastApiType: search
    description: Feature discovery for point-to-point logistics operations
    sequence:
      - key: search_LOGISTICS
        type: search
        unsolicited: false
        description: Buyer searches for point-to-point delivery options
        pair: on_search_LOGISTICS
        owner: BAP
        expect: true
        input:
          - name: retailCategory
            label: Select retail item category
            type: select
            values:
              - F&B
              - Grocery
              - Fashion
              - BPC
              - Electronics
              - Appliances
              - Home & Kitchen
              - Health & Wellness
              - Pharma
              - Auto components
              - C2C parcels
          - name: category
            label: Select a category
            type: select
            values:
              - Standard Delivery
              - Immediate Delivery
              - Next Day Delivery
              - Same Day Delivery
            payloadField: $.message.intent.category.id
          - name: paymentType
            label: Select payment type
            type: select
            values:
              - POST-FULFILLMENT
              - ON-ORDER
              - ON-FULFILLMENT
            payloadField: $.message.intent.payment.type
          - name: city_code
            label: Enter city code
            type: text
            payloadField: $.context.city
            default: "std:080"
          - name: start_gps
            label: Enter start gps coordinates
            type: text
            payloadField: $.message.intent.fulfillment.start.location.gps
            default: 12.4535,77.9283
          - name: end_gps
            label: Enter end gps coordinates
            type: text
            payloadField: $.message.intent.fulfillment.end.location.gps
            default: 12.4535,77.9283
          - name: start_code
            label: Enter start area code
            type: text
            payloadField: $.message.intent.fulfillment.start.location.address.area_code
            default: "560001"
          - name: end_code
            label: Enter end area code
            type: text
            payloadField: $.message.intent.fulfillment.end.location.address.area_code
            default: "560001"
          - name: feature_discovery
            label: Features supported
            type: checkbox
            options:
              - code: "00B"
                name: "Updated cancellation codes"
              - code: "00F"
                name: "ePOD"
              - code: "017"
                name: "Surge fee"
              - code: "019"
                name: "eWay bill"
              - code: "01A"
                name: "Cancellation terms"
              - code: "01C"
                name: "SLA metrics"
              - code: "01D"
                name: "Publish special capabilities"
              - code: "01E"
                name: "RCM self-declaration"
              - code: "01F"
                name: "Codified static terms"
              - code: "020"
                name: "Exchange customer support contact details"
              - code: "021"
                name: "Differential weight charges"
      - key: on_search_LOGISTICS
        type: on_search
        unsolicited: false
        description: Logistics provider responds with available delivery options
        pair: null
        owner: BPP
        input:
          - name: feature_discovery
            label: Features supported
            type: checkbox
            options:
              - code: "003"
                name: "Rate Card for P2P"
              - code: "004"
                name: "Rate Card for P2H2P"
              - code: "005"
                name: "Quick Commerce Logistics"
              - code: "006"
                name: "Milk Run Logistics"
              - code: "007"
                name: "Single pickup multi drop (SPMD)"
              - code: "008"
                name: "COD order"
              - code: "009"
                name: "Static OTP verification (pickup & delivery)"
              - code: "00A"
                name: "Static OTP verification (RTO)"
              - code: "00B"
                name: "Updated cancellation codes"
              - code: "00D"
                name: "Payment wallet"
              - code: "00F"
                name: "ePOD"
              - code: "010"
                name: "Call Masking"
              - code: "011"
                name: "Update delivery address"
              - code: "012"
                name: "Update pickup & delivery authorization"
              - code: "013"
                name: "Seller & buyer instructions"
              - code: "014"
                name: "Seller Creds"
              - code: "015"
                name: "Dynamic OTP verification (pickup & delivery)"
              - code: "016"
                name: "Dynamic OTP verification (RTO)"
              - code: "017"
                name: "Surge fee"
              - code: "018"
                name: "Partial RTO"
              - code: "019"
                name: "eWay bill"
              - code: "01A"
                name: "Cancellation terms"
              - code: "01B"
                name: "Reverse QC"
              - code: "01C"
                name: "SLA metrics"
              - code: "01D"
                name: "Publish special capabilities"
              - code: "01E"
                name: "RCM self-declaration"
              - code: "01F"
                name: "Codified static terms"
              - code: "020"
                name: "Exchange customer support contact details"
              - code: "021"
                name: "Differential weight charges"
              - code: "022"
                name: "RTO (with return)"
 