version: "3.8"

services:
  config-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: config-service-staging
    ports:
      - "${PORT:-5556}:${PORT:-5556}"
    env_file:
      - .env
    restart: always
