domain:
  - name: ONDC:TRV11
    versions:
      - id: 2.0.0
        usecase:
          - name: Metro
            flows: "./TRV11/V-2.0.0/metro/flows/index.yaml"
            supportedActions:
              $ref: "src/config/TRV11/V-2.0.0/metro/supportedActions/index.yaml"
          - name: Bus
            flows: "./TRV11/V-2.0.0/bus/flows/index.yaml"
      - id: 2.0.1
        usecase:
          - name: Metro
            flows: "./flows/TRV11/V-2.0.1/index.yaml"
