flows:
  - id: ORDER_FLOW_BASE_LINE
    description: User uses station code for searching bus
    sequence:
      - key: search1_LOGISTICS
        type: search
        unsolicited: false
        description: LBNP sends a search request
        pair: on_search1_LOGISTICS
        owner: BAP
        expect: true
      - key: on_search1_LOGISTICS
        type: on_search
        unsolicited: false
        description: LSP responds with catalog
        pair: null
        owner: BPP
      - key: init_LOGISTICS
        type: init
        unsolicited: false
        description: LBNP selects and initializes order
        pair: on_init_LOGISTICS
        owner: BAP
      - key: on_init_LOGISTICS
        type: on_init
        unsolicited: false
        description: LSP acknowledges and provides quote breakup
        pair: null
        owner: BPP
      - key: confirm_LOGISTICS
        type: confirm
        unsolicited: false
        description: LBNP sends order confirmation
        pair: on_confirm_LOGISTICS
        owner: BAP
      - key: on_confirm_LOGISTICS
        type: on_confirm
        unsolicited: false
        description: LSP accepts the order
        pair: null
        owner: BPP
      - key: update_LOGISTICS
        type: update
        unsolicited: false
        description: LBNP updates order details
        pair: on_update_LOGISTICS
        owner: BAP
      - key: on_update_LOGISTICS
        type: on_update
        unsolicited: false
        description: LSP updates order details
        pair: null
        owner: BPP
      - key: on_status_1_LOGISTICS
        type: on_status
        unsolicited: true
        description: LSP updates order status
        pair: null
        owner: BPP
      - key: on_status_1_LOGISTICS
        type: on_status
        unsolicited: true
        description: LSP updates order status
        pair: null
        owner: BPP
      - key: on_status_1_LOGISTICS
        type: on_status
        unsolicited: true
        description: LSP updates order status
        pair: null
        owner: BPP
      - key: track_LOGISTICS
        type: track
        unsolicited: false
        description: LBNP requests for tracking informatio
        pair: on_track_LOGISTICS
        owner: BAP
      - key: on_track_LOGISTICS
        type: on_track
        unsolicited: false
        description: LSP provides order tracking information (gps or url)
        pair: null
        owner: BPP
      - key: on_status_2_LOGISTICS
        type: on_status
        unsolicited: true
        description: LSP updates order status
        pair: null
        owner: BPP
  - id: RTO_FLOW
    description: User uses station code for searching bus
    sequence:
      - key: search1_LOGISTICS
        type: search
        unsolicited: false
        description: LBNP sends a search request
        pair: on_search1_LOGISTICS
        owner: BAP
        expect: true
      - key: on_search1_LOGISTICS
        type: on_search
        unsolicited: false
        description: LSP responds with catalog
        pair: null
        owner: BPP
      - key: init_LOGISTICS
        type: init
        unsolicited: false
        description: LBNP selects and initializes order
        pair: on_init_LOGISTICS
        owner: BAP
      - key: on_init_LOGISTICS
        type: on_init
        unsolicited: false
        description: LSP acknowledges and provides quote breakup
        pair: null
        owner: BPP
      - key: confirm_LOGISTICS
        type: confirm
        unsolicited: false
        description: LBNP sends order confirmation
        pair: on_confirm_LOGISTICS
        owner: BAP
      - key: on_confirm_LOGISTICS
        type: on_confirm
        unsolicited: false
        description: LSP accepts the order
        pair: null
        owner: BPP
      - key: update_LOGISTICS
        type: update
        unsolicited: false
        description: LBNP updates order details
        pair: on_update_LOGISTICS
        owner: BAP
      - key: on_update_LOGISTICS
        type: on_update
        unsolicited: false
        description: LSP updates order details
        pair: null
        owner: BPP
      - key: status_LOGISTICS
        type: status
        unsolicited: false
        description: LBNP statuss order details
        pair: on_status_1_LOGISTICS
        owner: BAP
      - key: on_status_1_LOGISTICS
        type: on_status
        unsolicited: false
        description: LSP updates order status
        pair: null
        owner: BPP
      - key: on_status_1_LOGISTICS
        type: on_status
        unsolicited: true
        description: LSP updates order status
        pair: null
        owner: BPP
      - key: on_status_1_LOGISTICS
        type: on_status
        unsolicited: true
        description: LSP updates order status
        pair: null
        owner: BPP
      - key: cancel_LOGISTICS
        type: cancel
        unsolicited: false
        description: LBNP requests for canceling informatio
        pair: on_cancel_LOGISTICS
        owner: BAP
      - key: on_cancel_LOGISTICS
        type: on_cancel
        unsolicited: false
        description: LSP provides order canceling information (gps or url)
        pair: null
        owner: BPP
