flows:
  - id: FULL_CATALOG
    description: User uses station code for searching bus
    sequence:
      - key: search
        type: search
        unsolicited: false
        description: LBNP sends a search request
        pair: on_search
        owner: BAP
        expect: true
      - key: on_search
        type: on_search
        unsolicited: false
        description: LSP responds with catalog
        pair: null
        owner: BPP
  - id: INCREMENTAL_CATALOG
    description: User uses station code for searching bus
    sequence:
      - key: search_1
        type: search
        unsolicited: false
        description: LBNP sends a search request
        pair: on_search_1
        owner: BAP
        expect: true
        input:
          - name: search_mode
            display: false
            default: start
      - key: on_search_1
        type: on_search
        unsolicited: false
        description: LSP responds with catalog
        pair: null
        owner: BPP
      - key: on_search_2
        type: on_search
        unsolicited: true
        description: LSP responds with catalog
        pair: null
        owner: BPP
      # - key: search_1
      #   type: search
      #   unsolicited: false
      #   description: LBNP sends a search request
      #   pair: ""
      #   owner: BAP
      #   expect: true
      #   input:
      #     - name: search_mode
      #       display: false
      #       default: stop
  - id: ORDER_FLOW
    description: User uses station code for searching bus
    sequence:
      - key: search
        type: search
        unsolicited: false
        description: LBNP sends a search request
        pair: on_search
        owner: BAP
        expect: true
      - key: on_search
        type: on_search
        unsolicited: false
        description: LSP responds with catalog
        pair: null
        owner: BPP
      - key: select
        type: select
        unsolicited: false
        pair: on_select
        owner: BAP
        expect: false
      - key: on_select
        type: on_select
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: init
        type: init
        unsolicited: false
        pair: on_init
        owner: BAP
        expect: false
      - key: on_init
        type: on_init
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: confirm
        type: confirm
        unsolicited: false
        pair: on_confirm
        owner: BAP
        expect: false
      - key: on_confirm
        type: on_confirm
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
  - id: OUT_OF_STOCK
    description: Retail 1.2.5 (Out Of Stock)
    sequence:
      - key: search
        type: search
        unsolicited: false
        pair: on_search_118
        owner: BAP
        expect: true
        description: BAP sends the search request
      - key: on_search_118
        type: on_search
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: BPP returns the full catalog refresh
      - key: select_out_of_stock
        type: select
        unsolicited: false
        pair: on_select_out_of_stock
        owner: BAP
        expect: false
        description: BAP may add unavailable or out-of-stock items to the cart
      - key: on_select_out_of_stock
        type: on_select
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: BPP returns item breakup when item is out of stock
      - key: select
        type: select
        unsolicited: false
        pair: on_select
        owner: BAP
        expect: false
        description: BAP select the item
      - key: on_select
        type: on_select
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description:
          BPP returns item breakup when item is in stock and offer applied
          (if any)
      - key: init
        type: init
        unsolicited: false
        pair: on_init
        owner: BAP
        expect: false
        description: Buyer initiate the product and send the updated fulfillment id
      - key: on_init
        type: on_init
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: Respond to init
      - key: confirm
        type: confirm
        unsolicited: false
        pair: on_confirm
        owner: BAP
        expect: false
        description: Buyer confirms product
      - key: on_confirm
        type: on_confirm
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: Seller Accepts confirmation
      - key: on_status_packed
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order packed
      - key: on_status_agent_assigned
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - agent assigned
      - key: on_status_picked
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order picked up
      - key: on_status_out_for_delivery
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order out for delivery
      - key: on_status_order_delivered
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order delivered
      - key: track
        type: track
        unsolicited: false
        pair: on_track
        owner: BAP
        expect: false
        description: BAP request to track the order
      - key: on_track
        type: on_track
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: BPP sends the tracking information
  - id: BUYER_CANCEL
    description: Retail 1.2.5 (Buyer Side Order Cancellation)
    sequence:
      - key: search
        type: search
        unsolicited: false
        pair: on_search_121
        owner: BAP
        expect: true
        description: BAP sends the search request
      - key: on_search_121
        type: on_search
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: BPP returns the full catalog refresh
      - key: select_122
        type: select
        unsolicited: false
        pair: on_select_123
        owner: BAP
        expect: false
        description: BAP select the item
      - key: on_select_123
        type: on_select
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description:
          BPP returns item breakup when item is in stock and offer applied
          (if any)
      - key: init_124
        type: init
        unsolicited: false
        pair: on_init_125
        owner: BAP
        expect: false
        description: Buyer initiate the product and send the updated fulfillment id
      - key: on_init_125
        type: on_init
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: Respond to init
      - key: confirm_126
        type: confirm
        unsolicited: false
        pair: on_confirm_127
        owner: BAP
        expect: false
        description: Buyer confirms product
      - key: on_confirm_127
        type: on_confirm
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: Seller Accepts confirmation
      - key: cancel
        type: cancel
        unsolicited: false
        pair: on_cancel
        owner: BAP
        expect: false
        description: Buyer request for the cancellation of the order
      - key: on_cancel
        type: on_cancel
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: Seller confirms the cancellation of the order
  - id: SELLER_CANCEL
    description: Retail 1.2.5 (Seller Side Order Cancellation RTO)
    sequence:
      - key: search
        type: search
        unsolicited: false
        pair: on_search_121
        owner: BAP
        expect: true
        description: BAP sends the search request
      - key: on_search_121
        type: on_search
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: BPP returns the full catalog refresh
      - key: select_122
        type: select
        unsolicited: false
        pair: on_select_130
        owner: BAP
        expect: false
        description: BAP select the item
      - key: on_select_130
        type: on_select
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description:
          BPP returns item breakup when item is in stock and offer applied
          (if any)
      - key: init_131
        type: init
        unsolicited: false
        pair: on_init_132
        owner: BAP
        expect: false
        description: Buyer initiate the product and send the updated fulfillment id
      - key: on_init_132
        type: on_init
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: Respond to init
      - key: confirm_133
        type: confirm
        unsolicited: false
        pair: on_confirm_134
        owner: BAP
        expect: false
        description: Buyer confirms product
      - key: on_confirm_134
        type: on_confirm
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: Seller Accepts confirmation
      - key: on_status_pending
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order pending
      - key: on_status_packed_136
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order packed
      - key: on_status_picked_137
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order picked up
      - key: on_status_out_for_delivery_138
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order out for delivery
      - key: on_cancel_rto
        type: on_cancel
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Order updates - seller side full-order cancellation
      - key: on_status_rto_delivereddisposed
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - rto order delivered
  - id: RETURN_WITH_LIQUIDATION
    description: Retail 1.2.5 (Liquidation)
    sequence:
      - key: search
        type: search
        unsolicited: false
        pair: on_search_141
        owner: BAP
        expect: true
        description: BAP sends the search request
      - key: on_search_141
        type: on_search
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: BPP returns the full catalog refresh
      - key: select_142
        type: select
        unsolicited: false
        pair: on_select_143
        owner: BAP
        expect: false
        description: BAP selects the item
      - key: on_select_143
        type: on_select
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description:
          BPP returns item breakup when item is in stock and offer applied
          (if any)
      - key: init_144
        type: init
        unsolicited: false
        pair: on_init_145
        owner: BAP
        expect: false
        description: Buyer initiates the product and sends the updated fulfillment ID
      - key: on_init_145
        type: on_init
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: Respond to init
      - key: confirm_146
        type: confirm
        unsolicited: false
        pair: on_confirm_147
        owner: BAP
        expect: false
        description: Buyer confirms product
      - key: on_confirm_147
        type: on_confirm
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        description: Seller accepts confirmation
      - key: on_status_pending_155
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order accepted
      - key: on_status_packed_156
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order packed
      - key: on_status_picked_157
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order picked up
      - key: on_status_out_for_delivery_158
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order out for delivery
      - key: on_status_order_delivered_159
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: Status updates - order delivered
      - key: update_liquidated
        type: update
        unsolicited: false
        pair: on_update_interim_liquidated
        owner: BAP
        expect: false
        description: BAP requests to return the items
      - key: on_update_interim_liquidated
        type: on_update
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: BPP sends the return initiate request
      - key: on_update_liquidated
        type: on_update
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        description: BPP approves return request and liquidates the items
      - key: update_liquidated_settlement
        type: update
        unsolicited: false
        pair: null
        owner: BAP
        expect: false
        description: Update settlement - liquidated
