flows:
  - id: FULL_CATALOG
    description: User uses station code for searching bus
    sequence:
      - key: search
        type: search
        unsolicited: false
        description: LBNP sends a search request
        pair: on_search
        owner: BAP
        expect: true
      - key: on_search
        type: on_search
        unsolicited: false
        description: LSP responds with catalog
        pair: null
        owner: BPP
  - id: INCREMENTAL_CATALOG
    description: User uses station code for searching bus
    sequence:
      - key: search_1
        type: search
        unsolicited: false
        description: LBNP sends a search request
        pair: on_search_1
        owner: BAP
        expect: true
        input:
          - name: search_mode
            display: false
            default: start
      - key: on_search_1
        type: on_search
        unsolicited: false
        description: LSP responds with catalog
        pair: null
        owner: BPP
      - key: on_search_2
        type: on_search
        unsolicited: true
        description: LSP responds with catalog
        pair: null
        owner: BPP
      # - key: search_1
      #   type: search
      #   unsolicited: false
      #   description: LBNP sends a search request
      #   pair: ""
      #   owner: BAP
      #   expect: true
      #   input:
      #     - name: search_mode
      #       display: false
      #       default: stop
  - id: ORDER_FLOW
    description: User uses station code for searching bus
    sequence:
      - key: search
        type: search
        unsolicited: false
        description: LBNP sends a search request
        pair: on_search
        owner: BAP
        expect: true
      - key: on_search
        type: on_search
        unsolicited: false
        description: LSP responds with catalog
        pair: null
        owner: BPP
      - key: select
        type: select
        unsolicited: false
        pair: on_select
        owner: BAP
        expect: false
      - key: on_select
        type: on_select
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: init
        type: init
        unsolicited: false
        pair: on_init
        owner: BAP
        expect: false
      - key: on_init
        type: on_init
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: confirm
        type: confirm
        unsolicited: false
        pair: on_confirm
        owner: BAP
        expect: false
      - key: on_confirm
        type: on_confirm
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
