flows:
  - id: FULL_CATALOG
    description: User uses station code for searching bus
    sequence:
      - key: search
        type: search
        unsolicited: false
        description: LBNP sends a search request
        pair: on_search
        owner: BAP
        expect: true
      - key: on_search
        type: on_search
        unsolicited: false
        description: LSP responds with catalog
        pair: null
        owner: BPP
  - id: INCREMENTAL_CATALOG
    description: User uses station code for searching bus
    sequence:
      - key: search_1
        type: search
        unsolicited: false
        description: LBNP sends a search request
        pair: on_search_1
        owner: BAP
        expect: true
      - key: on_search_1
        type: on_search
        unsolicited: false
        description: LSP responds with catalog
        pair: null
        owner: BPP
      - key: on_search_2
        type: on_search
        unsolicited: true
        description: LSP responds with catalog
        pair: null
        owner: BPP
