supportedActions:
  null: ["search"]
  search: ["on_search"]
  on_search: ["search", "select"]
  select: ["on_select"]
  on_select: ["init"]
  init: ["on_init"]
  on_init: ["init", "confirm"]
  confirm: ["on_confirm", "status"]
  on_confirm: ["status", "cancel", "on_status", "on_update"]
  status: ["on_status"]
  on_status: ["status", "cancel", "on_update"]
  cancel: ["on_cancel", "status"]
  on_cancel: ["cancel", "status"]

apiProperties:
  search:
    async_predecessor: null
    transaction_partner: []
  on_search:
    async_predecessor: "search"
    transaction_partner: ["search"]
  select:
    async_predecessor: null
    transaction_partner: ["search"]
  on_select:
    async_predecessor: "select"
    transaction_partner: ["select", "search", "on_search"]
  init:
    async_predecessor: null
    transaction_partner: ["select", "search", "on_search", "on_select"]
  on_init:
    async_predecessor: "init"
    transaction_partner: ["init", "select", "search", "on_search", "on_select"]
  confirm:
    async_predecessor: null
    transaction_partner: ["init", "on_init"]
  on_confirm:
    async_predecessor: "confirm"
    transaction_partner: ["init", "on_init", "confirm"]
  status:
    async_predecessor: null
    transaction_partner: ["init", "on_init", "confirm"]
  on_status:
    async_predecessor: "status"
    transaction_partner: ["init", "on_init", "confirm", "on_confirm"]
  cancel:
    async_predecessor: null
    transaction_partner: ["confirm", "on_confirm"]
  on_cancel:
    async_predecessor: "cancel"
    transaction_partner: ["confirm", "cancel", "on_confirm"]
